### ISSUE TITLE
Fuseau Horaire

### ISSUE THREAD

**Issue by SuwakoMmh** [Obito1903/CY-celcat#2]
Salut,

Je me permets de te signaler que tous les évènements du calendrier que tu publies sur ton site sont décalés d'une heure
J'ai pas encore téléchargé les changements que tu as fait donc je ne sais pas si ça vient de la maj du code ou d'un changement sur la manière dont tu génères le fichier.

**Comment by Obito1903** [comment]
oui effectivement je vais regardé ca plus en details.

**Comment by Obito1903** [comment]
Le problème venait du docker qui n’était pas sur la bonne timezone. Je ferme donc l'issue.
