### ISSUE TITLE
CY-TECH CELCAT

### ISSUE THREAD

**Issue by Adil11jr** [Obito1903/CY-celcat#7]
Hey, I am in CY-Tech from Paris, and I'd like to integrate CY-Tech's timetable into my Google calendar. In order to do that I have to download it in a (.ics) format, but I clearly don't know how to, and neither how to use your program to download it because I'm not really good at this.
I really need this, and I'd really appreciate your help.

**Comment by Obito1903** [comment]
This program needs to run on a server or at least on a computer that is on 24/7, then it will fetch the calendar and make it available either through the web or by writing an ICS file on your disk. 

If you really need it, I can add your calendar to the list of already available calendars. Please contact me on Discord for more detailed info.
